[package]
name = "markov_chain_sentence_generator_04"
version = "0.1.0"
authors = ["Kalam :p <63474858+YourKalamity@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
